name: 'Setup KMP Environment'
description: 'Setup Kotlin Multiplatform development environment with optimized caching'
author: 'Kelime İşlem Team'

inputs:
  java-version:
    description: 'Java version to use'
    required: false
    default: '17'

  gradle-cache-encryption-key:
    description: 'Encryption key for Gradle cache'
    required: false
    default: ''

  cache-read-only:
    description: 'Whether cache should be read-only'
    required: false
    default: 'false'

  dependency-graph-mode:
    description: 'Dependency graph mode: generate, generate-and-submit, or disabled'
    required: false
    default: 'generate'

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Gradle with enhanced caching
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-home-cache-cleanup: true
        cache-encryption-key: ${{ inputs.gradle-cache-encryption-key }}
        cache-read-only: ${{ inputs.cache-read-only }}
        cache-write-only: false
        generate-job-summary: true
        dependency-graph: ${{ inputs.dependency-graph-mode }}

    - name: Cache Kotlin/Native compiler
      uses: actions/cache@v4
      with:
        path: ~/.konan
        key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-konan-

    - name: Cache Gradle Wrapper
      uses: actions/cache@v4
      with:
        path: ~/.gradle/wrapper
        key: gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-wrapper-

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew

    - name: Validate Gradle Wrapper
      shell: bash
      run: ./gradlew --version

    - name: Set up environment variables
      shell: bash
      run: |
        echo "GRADLE_OPTS=-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true" >> $GITHUB_ENV
        echo "KOTLIN_COMPILER_EXECUTION_STRATEGY=in-process" >> $GITHUB_ENV
        echo "## 🚀 KMP Environment Setup" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${GITHUB_REF_NAME}" >> $GITHUB_STEP_SUMMARY
        echo "- **Java Version**: ${{ inputs.java-version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Cache Mode**: ${{ inputs.cache-read-only == 'true' && 'Read-only' || 'Read-write' }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Runner OS**: ${RUNNER_OS}" >> $GITHUB_STEP_SUMMARY