name: 'Setup Gradle Environment'
description: 'Sets up JDK and Gradle with optimal caching configuration'
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        # Use read-only cache for PRs to avoid cache pollution
        cache-read-only: ${{ github.event_name == 'pull_request' }}
        # Enable Gradle home cache cleanup to reduce cache size
        gradle-home-cache-cleanup: true
        # Enable dependency verification
        dependency-graph: generate-and-submit
    
    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew