name: 'Setup Gradle Environment'
description: 'Sets up JDK and Gradle with optimal caching configuration'
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4
      with:
        # Use read-only cache for PRs to avoid cache pollution
        cache-read-only: ${{ github.event_name == 'pull_request' }}
        # Enable Gradle home cache cleanup to reduce cache size
        gradle-home-cache-cleanup: true

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew