name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fail-fast-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup JDK and Gradle
      uses: ./.github/actions/setup
    
    - name: Validate Gradle setup
      run: ./gradlew help --no-daemon --quiet
    
    - name: Check Kotlin compilation (fail fast)
      run: ./gradlew compileKotlinJs compileKotlinWasm --no-daemon --quiet

  validate:
    runs-on: ubuntu-latest
    needs: fail-fast-check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis
    
    - name: Setup Gradle environment
      uses: ./.github/actions/setup-gradle
    
    - name: Run tests with coverage
      run: ./gradlew testDebugUnitTest koverXmlReport --build-cache --parallel
    
    - name: Run Android Lint
      run: ./gradlew lintDebug --build-cache --continue
    
    - name: SonarCloud Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonar --info --build-cache
    
    # Only upload to CodeCov if token is available (optional)
    - name: Upload coverage to Codecov
      if: ${{ env.CODECOV_TOKEN != '' }}
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./composeApp/build/reports/kover/report.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          composeApp/build/reports/tests/testDebugUnitTest/
          composeApp/build/test-results/testDebugUnitTest/
        retention-days: 7
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-reports
        path: |
          composeApp/build/reports/kover/
        retention-days: 7
    
    - name: Upload lint reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-reports
        path: |
          composeApp/build/reports/lint-results-*.html
          composeApp/build/reports/lint-results-*.xml
        retention-days: 7

  build:
    runs-on: ubuntu-latest
    needs: validate
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
    
    strategy:
      matrix:
        target: [debug, release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Gradle environment
      uses: ./.github/actions/setup-gradle
    
    - name: Build ${{ matrix.target }} APK
      run: ./gradlew assemble${{ matrix.target == 'debug' && 'Debug' || 'Release' }} --build-cache --parallel
    
    - name: Upload ${{ matrix.target }} APK
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}-apk
        path: composeApp/build/outputs/apk/${{ matrix.target }}/*.apk
        retention-days: 7
        if-no-files-found: error