name: CodeRabbit Auto-Fix Handler

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  handle-coderabbit:
    name: Process CodeRabbit Suggestions
    runs-on: ubuntu-latest
    if: |
      github.event.comment.user.login == 'coderabbitai' &&
      contains(github.event.comment.body, 'suggestion')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Extract and implement suggestions
        env:
          CODEGEN_API_KEY: ${{ secrets.CODEGEN_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          # Extract suggestions from comment
          COMMENT_BODY='${{ github.event.comment.body }}'

          echo "🤖 Processing CodeRabbit suggestions..."

          # Spawn Codegen agent to implement suggestions
          python .github/scripts/spawn_agent.py coderabbit "$COMMENT_BODY"

      - name: React to comment
        uses: actions/github-script@v7
        with:
          script: |
            // Add rocket reaction to show we're processing
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });

            // Add acknowledgment comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: `## 🤖 CodeRabbit Suggestions Acknowledged

              A Codegen.sh agent has been spawned to implement your suggestions.
              The fixes will be committed directly to this PR shortly.

              Track progress at: https://codegen.com/`
            });