name: CodeRabbit to Codegen Integration

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write

jobs:
  trigger-codegen:
    name: Auto-trigger Codegen for CodeRabbit Issues
    runs-on: ubuntu-latest
    if: |
      github.event.comment.user.login == 'coderabbitai' &&
      (contains(github.event.comment.body, '⚠️') ||
       contains(github.event.comment.body, '🔴') ||
       contains(github.event.comment.body, 'Potential issue') ||
       contains(github.event.comment.body, 'Critical') ||
       contains(github.event.comment.body, 'Major'))

    steps:
      - name: Debug event data
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Comment user login: ${{ github.event.comment.user.login }}"
          echo "Comment body contains ⚠️: ${{ contains(github.event.comment.body, '⚠️') }}"
          echo "Comment body contains 🔴: ${{ contains(github.event.comment.body, '🔴') }}"
          echo "Comment body contains 'Potential issue': ${{ contains(github.event.comment.body, 'Potential issue') }}"

      - name: Trigger Codegen
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body;
            const commentUrl = context.payload.comment.html_url;

            // Extract the issue/suggestion from CodeRabbit comment
            const lines = comment.split('\n');
            const issueLine = lines.find(line =>
              line.includes('⚠️') ||
              line.includes('🔴') ||
              line.includes('**')
            ) || lines[0];

            // Create Codegen mention
            const codegenComment = `@codegen-sh Please fix the issue identified by CodeRabbit:

${issueLine}

Reference: ${commentUrl}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: codegenComment
            });

      - name: React to CodeRabbit comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });