name: Codegen Check Monitor

on:
  check_suite:
    types: [completed]
  workflow_run:
    workflows: ["KMP CI/CD Pipeline"]
    types: [completed]

permissions:
  pull-requests: write
  issues: write

jobs:
  notify-codegen-on-failure:
    name: Notify Codegen of Failed Checks
    runs-on: ubuntu-latest
    if: |
      (github.event.check_suite.conclusion == 'failure' ||
       github.event.workflow_run.conclusion == 'failure') &&
      github.event.pull_request.number

    steps:
      - name: Comment to trigger Codegen
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const checkName = context.payload.check_suite?.app?.name ||
                            context.payload.workflow_run?.name || 'CI';

            const comment = `@codegen The ${checkName} check has failed. Please investigate and fix the issues.

            Check Details:
            - Status: Failed ❌
            - PR: #${pr.number}
            - Branch: ${pr.head.ref}

            Please ensure all tests pass and the build is successful.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: comment
            });

            console.log(`Notified Codegen about failed ${checkName} check`);