name: Debug Workflow Context

on:
  push:
    branches: ['fix/ci-workflow-failures-and-tests']

jobs:
  debug-context:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub context
        run: |
          echo "=== GitHub Context Debug ==="
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "Base ref: ${{ github.base_ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
          
          echo "=== Conditional Tests ==="
          echo "startsWith(github.ref, 'refs/tags/'): ${{ startsWith(github.ref, 'refs/tags/') }}"
          echo "github.event_name == 'workflow_dispatch': ${{ github.event_name == 'workflow_dispatch' }}"
          echo "Combined condition: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}"
          
          echo "=== Secret Check ==="
          echo "CLAUDE_CODE_OAUTH_TOKEN exists: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN != '' }}"
