name: PR Check

permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  coverage-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run tests with coverage
      run: ./gradlew testDebugUnitTest koverXmlReport

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Add coverage comment to PR
      uses: mi-kas/kover-report@v1
      with:
        path: composeApp/build/reports/kover/report.xml
        token: ${{ secrets.PAT_COVERAGE_TOKEN }}
        title: Code Coverage
        update-comment: true
        min-coverage-overall: 80
        min-coverage-changed-files: 80
    
    - name: Verify coverage threshold
      run: ./gradlew koverVerify