name: PR Check

permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  coverage-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: true
        gradle-home-cache-cleanup: true

    - name: Run tests with coverage
      run: ./gradlew testDebugUnitTest koverXmlReport --parallel --build-cache

    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        if [ -n "$SONAR_TOKEN" ]; then
          ./gradlew sonar --info --build-cache
        else
          echo "Skipping SonarCloud analysis - SONAR_TOKEN not set"
        fi
      continue-on-error: true

    - name: Add coverage comment to PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: mi-kas/kover-report@v1
      continue-on-error: true
      with:
        path: composeApp/build/reports/kover/report.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Code Coverage
        update-comment: true
        min-coverage-overall: 70
        min-coverage-changed-files: 60

    # Make coverage verification non-blocking (warning only)
    - name: Verify coverage threshold
      continue-on-error: true
      run: ./gradlew koverVerify